# Generated by Django 5.0 on 2023-12-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcallapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRecord',
            new_name='RoomRecord',
        ),
    ]
