# Generated by Django 4.2.5 on 2023-12-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcallapp', '0002_rename_userrecord_roomrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomrecord',
            old_name='created_at',
            new_name='joined_at',
        ),
    ]
